AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A starter AWS Lambda function.
Resources:
  handler_one:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler1
      Runtime: python3.6
      CodeUri: .
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /one
            Method: get
  handler_two:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler2
      Runtime: python3.6
      CodeUri: .
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /two
            Method: get